"""Add arming and alarm state event tables

Revision ID: 987a4bb5fd7c
Revises: c3e998a8b0b0
Create Date: 2026-07-28 23:24:51.282612

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '987a4bb5fd7c'
down_revision: Union[str, Sequence[str], None] = 'c3e998a8b0b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alarm_state_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('partition_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('trigger_type', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alarm_state_events_created_at'), 'alarm_state_events', ['created_at'], unique=False)
    op.create_index(op.f('ix_alarm_state_events_id'), 'alarm_state_events', ['id'], unique=False)
    op.create_index(op.f('ix_alarm_state_events_partition_id'), 'alarm_state_events', ['partition_id'], unique=False)
    op.create_table('arming_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('partition_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('last_user', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_arming_events_created_at'), 'arming_events', ['created_at'], unique=False)
    op.create_index(op.f('ix_arming_events_id'), 'arming_events', ['id'], unique=False)
    op.create_index(op.f('ix_arming_events_partition_id'), 'arming_events', ['partition_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_arming_events_partition_id'), table_name='arming_events')
    op.drop_index(op.f('ix_arming_events_id'), table_name='arming_events')
    op.drop_index(op.f('ix_arming_events_created_at'), table_name='arming_events')
    op.drop_table('arming_events')
    op.drop_index(op.f('ix_alarm_state_events_partition_id'), table_name='alarm_state_events')
    op.drop_index(op.f('ix_alarm_state_events_id'), table_name='alarm_state_events')
    op.drop_index(op.f('ix_alarm_state_events_created_at'), table_name='alarm_state_events')
    op.drop_table('alarm_state_events')
    # ### end Alembic commands ###
